ICE-10908 Capture the NoClassDefFoundError error in QueueConsumerTask.run that occurs when application is removed from file system and QueueConsumerTask is not disposed yet by the servlet's container context disposed event.